# Generated by Django 5.2.8 on 2025-11-25 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField(help_text='Matrix and generation data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_damage', models.IntegerField(default=1)),
                ('cooldown', models.IntegerField(default=0, help_text='Cooldown in turns')),
                ('shape_type', models.CharField(choices=[('single', 'Single Tile'), ('ranged_single', 'Ranged Single Tile'), ('line', 'Line'), ('aoe', 'Area of Effect'), ('cross', 'Cross')], default='single', max_length=20)),
                ('range', models.IntegerField(default=0, help_text='Range for ranged spells')),
                ('radius', models.IntegerField(default=0, help_text='Radius for AoE spells')),
                ('visual_config', models.JSONField(default=dict, help_text='JSON configuration for visual effects (type, style, etc.)')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_damage', models.IntegerField(default=1)),
                ('sprite_path', models.CharField(help_text="Path to the sprite image, e.g., 'art/weapons/sword.png'", max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_health', models.IntegerField(default=10)),
                ('max_health', models.IntegerField(default=10)),
                ('base_damage', models.IntegerField(default=1)),
                ('base_movement', models.IntegerField(default=5)),
                ('sprite_path_idle', models.CharField(default='art/player/Idle.png', max_length=255)),
                ('sprite_path_attack', models.CharField(default='art/player/Attack1.png', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('unlocked_spells', models.ManyToManyField(blank=True, related_name='characters', to='game.spell')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='game.weapon')),
            ],
        ),
    ]
